# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-08-02 15:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_account_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='civi',
            name='author',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='civis', to='api.Account'),
        ),
        migrations.AlterField(
            model_name='civi',
            name='thread',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='civis', to='api.Thread'),
        ),
    ]
